- name: enable universe repo
  apt_repository:
    repo: "deb http://archive.ubuntu.com/ubuntu {{ ansible_distribution_release|lower }} universe"
    state: present

- name: install ssh config file
  copy: dest=/etc/ssh/sshd_config src=sshd_config mode=0600
  notify: restart ssh

- name: create local admin users
  user:
    append: yes
    groups: sudo
    name: "{{ item.username }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items: "{{ qb_base_admin_users }}"

- name: set local admin private keys
  authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.key }}"
  with_items: "{{ qb_base_authorized_keys }}"

- name: remove obsolete users
  user:
    name: "{{ item }}"
    state: absent
    remove: true
  with_items: "{{ qb_base_users_to_remove }}"
