- hosts: all
  roles:
    - role: qb-base
      tags:
        - qb-base

    - role: qb-storage
      tags:
        - qb-storage
      when:
        - qb_storage_enabled

    - role: node-exporter
      tags:
        - node-exporter

- import_playbook: cluster.yml

- hosts: gfs-cluster
  roles:
    - role: ./contrib/network-storage/glusterfs/roles/uninstall
      tags:
        - qb-uninstall-glusterfs
