- hosts: all
  roles:
    - role: qb-base
      tags:
        - qb-base

    - role: qb-storage
      tags:
        - qb-storage
      when:
        - qb_storage_enabled

    - role: node-exporter
      tags:
        - node-exporter

- import_playbook: cluster.yml

- hosts: all
  roles:
    - role: qb-post-install
      tags:
        - qb-post-install

# TODO heccetti :(
# - import_playbook: contrib/network-storage/heketi/heketi.yml
