- name: create cert-manager cluster issuer
  k8s:
    state: present
    definition:
      apiVersion: certmanager.k8s.io/v1alpha1
      kind: ClusterIssuer
      metadata:
        name: letsencrypt-prod
      spec:
        acme:
          email: "{{ cert_manager_email }}"
          http01: {}
          privateKeySecretRef:
            key: ""
            name: letsencrypt-prod
          server: https://acme-v02.api.letsencrypt.org/directory
